language: r
warnings_are_errors: true
sudo: false
cache: packages
env:
  global:
  - secure: fiyGwDpuFeKotrOqSsRpHr8f3eAjK3pfUBoW7PIqa4rAzuvPR2Ft2j/a2EvsuPlXwxsb7i9pjtbSBXIHoLngCEJ6kDNOCPeKCLNGW8SEWImQC18ThNcCOrD8rdgdON3IeZbS0mWWJqfK6CUELeuZAEt2pqlmLa+0TrNKPW8PTls=
  - secure: Uvjp8cUwYrzVmEVTh36PG10VdEy+uLl6Nx/h47/semGooGO3VjU43ZLrliZ2dTPEQ/7mYuHibte9zpvVV3CE0Ia0xmqqSSzmREwUNVFdQwPFcfUGaZdz6r6sM/9FFksmO4EuD0R5ehbFHz3CJbO+ZXgJAHcItDNmF2fbJL8VdM8=
  - NOT_CRAN="true"
